# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-20 02:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0006_auto_20171023_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='gender',
            new_name='sex',
        ),
    ]
