# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-20 21:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0007_auto_20171120_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
